spring.application.name=OntapGK-2

spring.datasource.url=jdbc:mysql://localhost:3306/ql_sanpham?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true